# Generated by Django 5.1.5 on 2025-02-02 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operatori', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='masterdata.operatore')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='operatore',
            name='zone',
            field=models.ManyToManyField(related_name='operatori', through='masterdata.Assignment', to='masterdata.zone'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('pickup_date', models.DateField()),
                ('tolerance_before', models.IntegerField(default=0, help_text='Giorni di tolleranza prima della data prevista')),
                ('tolerance_after', models.IntegerField(default=0, help_text='Giorni di tolleranza dopo la data prevista')),
                ('last_pickup_datetime', models.DateTimeField(blank=True, null=True)),
                ('ragionesociale', models.CharField(max_length=50)),
                ('indirizzo', models.CharField(blank=True, max_length=100, null=True)),
                ('cap', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('sito_web', models.CharField(blank=True, max_length=200, null=True)),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clienti', to='masterdata.zone')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='masterdata.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('operatore', 'zone', 'date')},
        ),
    ]
