# Generated by Django 5.1.5 on 2025-02-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_rename_zone_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='name',
        ),
    ]
