# Generated by Django 5.1.5 on 2025-02-05 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_remove_cliente_address_remove_cliente_name'),
        ('pickup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='status',
            field=models.CharField(default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clienti', models.ManyToManyField(related_name='itineraries', to='masterdata.cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='masterdata.operatore')),
            ],
            options={
                'unique_together': {('operatore', 'date')},
            },
        ),
    ]
